[package]
name = "tree"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = "4.5.23"
csv = "1.3.1"
hex_color = "3.0.0"
reqwest = {version = "0.12.9", features = ["blocking"]}
serde = { version = "1.0.216", features = ["derive"] }
serde_json = "1.0.134"
tokio = "1.42.0"
webbrowser = "1.0.3"
